INSERT INTO CURRENCY_MAPPING (CURRENCY_CODE, CURRENCY_NAME_ZH) VALUES ('USD', '美元');
INSERT INTO CURRENCY_MAPPING (CURRENCY_CODE, CURRENCY_NAME_ZH) VALUES ('GBP', '英鎊');
INSERT INTO CURRENCY_MAPPING (CURRENCY_CODE, CURRENCY_NAME_ZH) VALUES ('EUR', '歐元');
