DROP TABLE IF EXISTS CURRENCY_MAPPING;

CREATE TABLE CURRENCY_MAPPING (
      CURRENCY_CODE VARCHAR(5) NOT NULL,
      CURRENCY_NAME_ZH VARCHAR(10) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      PRIMARY KEY (CURRENCY_CODE)
);

COMMENT ON TABLE CURRENCY_MAPPING IS
'幣別對照表，儲存幣別代碼與中文名稱';
COMMENT ON COLUMN CURRENCY_MAPPING.CURRENCY_CODE IS
'幣別代碼（ISO 4217），作為主鍵，例如 USD、EUR、GBP';
COMMENT ON COLUMN CURRENCY_MAPPING.CURRENCY_NAME_ZH IS
'幣別中文名稱，用於顯示，例如 美元、歐元';
COMMENT ON COLUMN CURRENCY_MAPPING.CREATED_AT IS
'資料建立時間';
COMMENT ON COLUMN CURRENCY_MAPPING.UPDATED_AT IS
'資料最後更新時間';
